@startuml
title mybatis 执行语句相关类图

interface Executor
class Configuration
together {
    interface SqlSessionFactory
    class DefaultSqlSessionFactory
    interface SqlSession
    class DefaultSqlSession
}

DefaultSqlSessionFactory .up.> SqlSessionFactory
DefaultSqlSession .up.> SqlSession

DefaultSqlSessionFactory -up-o Configuration
DefaultSqlSession -up-o Configuration

DefaultSqlSession .left.* Executor

@enduml